name: Daily update

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Git config
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Run script
      run: ./update.sh
      env:
        STEAM_PUBLIC_API_KEY: ${{ secrets.STEAM_PUBLIC_API_KEY }}
        STEAM_PUBLISHER_API_KEY: ${{ secrets.STEAM_PUBLISHER_API_KEY }}
